'use client';
import { Document, Page, Text, View, StyleSheet, BlobProvider } from '@react-pdf/renderer';
import React from 'react';
import { formatRupees } from '@/lib/money';
import { DeductionCategory } from '@/lib/rules/types';

type Props = {
  case: {
    tenantName: string;
    landlordName: string;
    propertyAddress: string;
    depositAmount: number;
  };
  deductions: Array<{
    category: DeductionCategory;
    amountAllowed: number;
    reasoning: string;
    citedAuthority: string;
  }>;
  settlementAmount: number;
  settlementTimestamp: string;
};

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica' },
  header: { fontSize: 18, fontWeight: 'bold', marginBottom: 8, color: '#0f172a' },
  subheader: { fontSize: 10, color: '#64748b', marginBottom: 20 },
  section: { marginBottom: 12 },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', marginBottom: 4, color: '#0f172a' },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 3, borderBottom: '1pt solid #e2e8f0' },
  rowLabel: { color: '#475569' },
  rowValue: { fontWeight: 'bold' },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 6, borderTop: '2pt solid #0f172a', marginTop: 6 },
  totalLabel: { fontWeight: 'bold', fontSize: 12 },
  totalValue: { fontWeight: 'bold', fontSize: 14, color: '#059669' },
  consent: { marginTop: 20, paddingTop: 10, borderTop: '1pt solid #cbd5e1' },
  consentRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
  footer: { marginTop: 30, fontSize: 8, color: '#94a3b8', textAlign: 'center' }
});

const CATEGORY_LABELS: Record<DeductionCategory, string> = {
  painting: 'Painting', fixtures: 'Fixtures & fittings', utilities: 'Utilities',
  unpaid_rent: 'Unpaid rent', cleaning: 'Cleaning'
};

function PdfDoc({ case: c, deductions, settlementAmount, settlementTimestamp }: Props) {
  const totalAllowed = deductions.reduce((s, d) => s + d.amountAllowed, 0);
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>DEPOSIT SETTLEMENT AGREEMENT</Text>
        <Text style={styles.subheader}>Generated by RentSettle · {settlementTimestamp}</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Parties</Text>
          <View style={styles.row}><Text style={styles.rowLabel}>Tenant</Text><Text>{c.tenantName}</Text></View>
          <View style={styles.row}><Text style={styles.rowLabel}>Landlord</Text><Text>{c.landlordName}</Text></View>
          <View style={styles.row}><Text style={styles.rowLabel}>Property</Text><Text>{c.propertyAddress}</Text></View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Deduction Breakdown</Text>
          {deductions.map(d => (
            <View key={d.category} style={{ marginBottom: 4 }}>
              <View style={styles.row}>
                <Text style={styles.rowLabel}>{CATEGORY_LABELS[d.category]}</Text>
                <Text style={d.amountAllowed === 0 ? { color: '#059669' } : styles.rowValue}>
                  {d.amountAllowed === 0 ? 'DENIED' : formatRupees(d.amountAllowed)}
                </Text>
              </View>
              {d.amountAllowed > 0 && (
                <Text style={{ fontSize: 8, color: '#64748b', marginTop: 1 }}>{d.citedAuthority}</Text>
              )}
            </View>
          ))}
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Total deductions allowed</Text>
            <Text style={styles.totalValue}>{formatRupees(totalAllowed)}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Settlement</Text>
          <View style={styles.row}>
            <Text style={styles.rowLabel}>Original deposit</Text>
            <Text>{formatRupees(c.depositAmount)}</Text>
          </View>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Agreed refund to tenant</Text>
            <Text style={styles.totalValue}>{formatRupees(settlementAmount)}</Text>
          </View>
        </View>

        <View style={styles.consent}>
          <Text style={styles.sectionTitle}>Digital Consent</Text>
          <View style={styles.consentRow}>
            <View>
              <Text style={{ fontSize: 9, color: '#64748b' }}>Tenant signature</Text>
              <Text style={{ fontFamily: 'Helvetica-Bold' }}>{c.tenantName}</Text>
              <Text style={{ fontSize: 8, color: '#94a3b8' }}>{settlementTimestamp}</Text>
            </View>
            <View>
              <Text style={{ fontSize: 9, color: '#64748b' }}>Landlord signature</Text>
              <Text style={{ fontFamily: 'Helvetica-Bold' }}>{c.landlordName}</Text>
              <Text style={{ fontSize: 8, color: '#94a3b8' }}>{settlementTimestamp}</Text>
            </View>
          </View>
        </View>

        <Text style={styles.footer}>
          RentSettle applies federal and Karnataka-specific law plus standard industry practices.
          Not legal advice. Disputing parties retain rights to pursue Rent Control Court.
        </Text>
      </Page>
    </Document>
  );
}

export function PdfSettlement(props: Props) {
  return (
    <BlobProvider document={<PdfDoc {...props} />}>
      {({ loading, blob, url }) => {
        const href = url ?? (blob ? URL.createObjectURL(blob) : '#');
        const filename = `RentSettle-${props.case.tenantName.replace(/\s+/g, '-')}.pdf`;
        return (
          <a
            href={href}
            download={filename}
            className={`group inline-flex items-center gap-3 rounded-lg border border-saffron bg-saffron px-10 py-5 text-paper transition-all hover:bg-ink hover:border-ink ${loading ? 'pointer-events-none opacity-60' : ''}`}
          >
            <span className="text-sm font-semibold uppercase tracking-widest">
              {loading ? 'Generating…' : 'Download settlement PDF'}
            </span>
            <span className="font-mono text-sm transition-transform group-hover:translate-x-1">→</span>
          </a>
        );
      }}
    </BlobProvider>
  );
}
